import {
  Router,
  type IRouter,
  type Request,
  type Response,
  type NextFunction,
} from "express";
import { z } from "zod";
import { db, disavowDomainsTable } from "@workspace/db";
import { eq, desc } from "drizzle-orm";
import { requireAdmin } from "../lib/routeHelpers";

const router: IRouter = Router();

const DisavowBody = z.object({
  domain: z.string().min(1).max(253),
  reason: z.string().max(1000).optional(),
});

router.get("/admin/disavow/export", requireAdmin, async (req, res, next) => {
  try {
    const rows = await db
      .select()
      .from(disavowDomainsTable)
      .orderBy(desc(disavowDomainsTable.createdAt));
    const lines = [
      "# Disavow file generated by FintechPressHub",
      `# Generated: ${new Date().toISOString()}`,
      "",
      ...rows.map((r) =>
        r.reason
          ? `# ${r.reason}\ndomain:${r.domain}`
          : `domain:${r.domain}`,
      ),
    ];
    res.setHeader("Content-Type", "text/plain; charset=utf-8");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="disavow-${new Date().toISOString().slice(0, 10)}.txt"`,
    );
    res.send(lines.join("\n") + "\n");
  } catch (err) {
    next(err);
  }
});

router.get("/admin/disavow", requireAdmin, async (req, res, next) => {
  try {
    const rows = await db
      .select()
      .from(disavowDomainsTable)
      .orderBy(desc(disavowDomainsTable.createdAt));
    res.json(rows);
  } catch (err) {
    next(err);
  }
});

router.post("/admin/disavow", requireAdmin, async (req, res, next) => {
  try {
    const body = DisavowBody.parse(req.body);
    const [row] = await db
      .insert(disavowDomainsTable)
      .values({
        domain: body.domain,
        reason: body.reason,
        addedBy: req.user?.email ?? "admin",
      })
      .returning();
    res.status(201).json(row);
  } catch (err) {
    if (err instanceof z.ZodError) {
      res.status(400).json({ error: "Invalid body", issues: err.issues });
      return;
    }
    if (
      err &&
      typeof err === "object" &&
      "code" in err &&
      (err as { code?: string }).code === "23505"
    ) {
      res.status(409).json({ error: "Domain already in disavow list" });
      return;
    }
    next(err);
  }
});

router.delete("/admin/disavow/:id", requireAdmin, async (req, res, next) => {
  const id = Number(req.params["id"]);
  if (!Number.isFinite(id) || id <= 0) {
    res.status(400).json({ error: "Invalid id" });
    return;
  }
  try {
    const [row] = await db
      .delete(disavowDomainsTable)
      .where(eq(disavowDomainsTable.id, id))
      .returning();
    if (!row) {
      res.status(404).json({ error: "Not found" });
      return;
    }
    res.json({ ok: true, deleted: row });
  } catch (err) {
    next(err);
  }
});

export default router;
