import { Router, type IRouter, type Request, type Response } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import adminAuthRouter from "./adminAuth";
import blogRouter from "./blog";
import pricingRouter from "./pricing";
import servicesRouter from "./services";
import testimonialsRouter from "./testimonials";
import statsRouter from "./stats";
import contactRouter from "./contact";
import guestPostsRouter from "./guestPosts";
import newsletterRouter from "./newsletter";
import authorNewsletterRouter from "./authorNewsletter";
import adminAuthorSubscribersRouter from "./adminAuthorSubscribers";
import adminNewsletterRouter from "./adminNewsletter";
import pitchRouter from "./pitch";
import ogRouter from "./og";
import toolsRouter from "./tools";
import commissioningTopicsRouter from "./commissioningTopics";
import sitemapHealthRouter from "./sitemapHealth";
import hreflangCheckAdminRouter from "./hreflangCheckAdmin";
import auditRouter from "./audit";
import notificationsRouter from "./notifications";
import adminModerationRouter from "./adminModeration";
import adminDashboardRouter from "./adminDashboard";
import adminAnalyticsRouter from "./adminAnalytics";
import contentReportsRouter from "./contentReports";
import authorPhotosRouter from "./authorPhotos";
import authorPhotoRequestsRouter from "./authorPhotoRequests";
import authorsRouter from "./authors";
import sitemapPingRouter from "./sitemapPing";
import seoPerformanceRouter from "./seoPerformance";
import glossaryRouter from "./glossary";
import disavowRouter from "./disavow";
import locationsRouter from "./locations";
import referringDomainsRouter from "./referringDomains";
import vitalsRouter from "./vitals";
import categoryRssRouter from "./categoryRss";
import pressMentionsRouter from "./pressMentions";
import adminSchemaTestRouter from "./adminSchemaTest";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(adminAuthRouter);
router.use(blogRouter);
router.use(pricingRouter);
router.use(servicesRouter);
router.use(testimonialsRouter);
router.use(statsRouter);
router.use(contactRouter);
router.use(guestPostsRouter);
router.use(newsletterRouter);
router.use(authorNewsletterRouter);
router.use(adminAuthorSubscribersRouter);
router.use(adminNewsletterRouter);
router.use(pitchRouter);
router.use(ogRouter);
router.use(toolsRouter);
router.use(commissioningTopicsRouter);
router.use(sitemapHealthRouter);
router.use(hreflangCheckAdminRouter);
router.use(auditRouter);
router.use(notificationsRouter);
router.use(adminModerationRouter);
router.use(adminDashboardRouter);
router.use(adminAnalyticsRouter);
router.use(contentReportsRouter);
router.use(authorPhotosRouter);
router.use(authorPhotoRequestsRouter);
router.use(authorsRouter);
router.use(sitemapPingRouter);
router.use(seoPerformanceRouter);
router.use(glossaryRouter);
router.use(disavowRouter);
router.use(locationsRouter);
router.use(referringDomainsRouter);
router.use(vitalsRouter);
router.use(categoryRssRouter);
router.use(pressMentionsRouter);
router.use(adminSchemaTestRouter);

// JSON 404 fallback for unmatched /api/* routes — must come last so it
// doesn't shadow any route registered above.
router.use((_req: Request, res: Response) => {
  res.status(404).json({ error: "Not found" });
});

export default router;
