// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/queue-reorder/QueueReorder.tsx": () => import("../components/mockups/queue-reorder/QueueReorder.tsx")
};
