import { useDocumentTitle } from "@/hooks/use-document-title";
import { PageHero } from "@/components/PageHero";

export default function EditorialGuidelines() {
  useDocumentTitle("Editorial Guidelines | FintechPressHub");

  return (
    <div className="min-h-screen bg-background">
      <PageHero
        eyebrow="Editorial"
        title={<>Editorial Guidelines</>}
        description="The standards we hold our internal writers, guest contributors, and client deliverables to — covering accuracy, sourcing, AI usage, tone, and compliance."
      />
      <div className="container mx-auto px-4 max-w-3xl py-20">
        <div className="prose prose-lg dark:prose-invert max-w-none">
          <p className="text-muted-foreground mb-8">Last updated: October 1, 2023</p>
          
          <p>FintechPressHub is committed to publishing accurate, authoritative, and actionable content for the financial technology industry. Whether you are an internal writer, a guest contributor, or a client reviewing our work, these guidelines dictate our standards.</p>
          
          <h2>1. Accuracy & Fact-Checking</h2>
          <p>The financial industry is highly regulated. All content must prioritize accuracy above all else.</p>
          <ul>
            <li>All statistics, claims, and data points must be linked to a credible, primary source (e.g., McKinsey, Plaid, SEC filings, recognized industry reports).</li>
            <li>Do not cite competitors as primary sources unless necessary for context.</li>
            <li>Ensure that descriptions of financial products (e.g., credit cards, loans, crypto assets) comply with standard marketing regulations (e.g., avoiding absolute guarantees of returns).</li>
          </ul>

          <h2>2. AI Policy</h2>
          <p>We do not publish unedited AI-generated content. While AI tools may be used for outlining, research assistance, or ideation, the final prose, analysis, and unique insights must be generated by a human subject matter expert. Content found to be heavily AI-generated will be rejected.</p>

          <h2>3. Voice and Tone</h2>
          <p>Our brand voice is <strong>Expert, Confident, and Precise</strong>.</p>
          <ul>
            <li><strong>Be direct:</strong> Avoid fluff, passive voice, and unnecessary jargon.</li>
            <li><strong>Be professional, not academic:</strong> Write for an educated B2B audience (Founders, CMOs, Product Managers), but keep it readable and engaging.</li>
            <li><strong>Show, don't tell:</strong> Use real-world examples and case studies rather than theoretical concepts.</li>
          </ul>

          <h2>4. Originality</h2>
          <p>All content must be 100% original. We run all submissions through plagiarism checkers. We do not accept syndicated content or articles that have been published elsewhere.</p>

          <h2>5. Outbound Linking</h2>
          <p>We encourage linking to high-quality external resources to provide context.</p>
          <ul>
            <li>Links must naturally fit the context of the sentence.</li>
            <li>We do not accept links to low-quality sites, essay writing services, gambling, adult content, or predatory lending sites.</li>
            <li>Any undisclosed sponsored links will result in the immediate removal of the article and a ban on the contributor.</li>
          </ul>
        </div>
      </div>
    </div>
  );
}
